# yaml-language-server: $schema=https://spec.openapis.org/oas/3.1/schema/2025-09-15

openapi: 3.1.0
info:
  title: Social Maps API
  summary: A free & open API for reviewing Points of Interest (POIs), complementing OpenStreetMap.
  contact:
    name: Bora M. Alper
    email: bora@boramalper.org
  version: 0.1.0
servers:
  - url: https://api.socialmaps.org/
paths:
  /v1/places/lookup:
    get:
      tags:
        - Places
      summary: Look up a Place
      description: |
        Look up a Place by its name and geographic coordinates.

        Because OpenStreetMap IDs are not permanent, we require the client to
        look up Places by their name instead and provide their geographic
        coordinates as well to narrow down the search (currently to a 10-metre
        radius).

        The API tolerates small differences between the name provided by the
        client and the name on record.
      parameters:
        - name: name
          in: query
          required: true
          schema:
            type: string
            example: "The Blackrock Castle"
            maxLength: 256
        - name: lat
          in: query
          required: true
          schema:
            type: number
            format: double
            minimum: -90
            maximum: +90
            example: 51.8216
        - name: lon
          in: query
          required: true
          schema:
            type: number
            format: double
            minimum: -180
            maximum: +180
            example: -8.8556
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Place'
        '404':
          description: Not Found
  /v1/places/{place_id}:
    get:
      tags:
        - Places
      summary: Retrieve a Place
      parameters:
        - name: place_id
          in: path
          required: true
          schema:
            $ref: '#/components/schemas/Place/properties/id'
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Place'
        '404':
          description: Not Found
  /v1/places/{place_id}/reviews:
    get:
      tags:
        - Reviews
      summary: List Reviews of a Place
      parameters:
        - name: place_id
          in: path
          required: true
          schema:
            $ref: '#/components/schemas/Place/properties/id'
          example: plc_nReHKJVfxZbhxmvi36r4rQ
        - name: order
          in: query
          schema:
            type: string
            default: 'most_recent'
            enum:
              - 'most_recent'
              - 'most_helpful'
            x-enum-descriptions:
              most_recent: Reviews created last are returned first.
              most_helpful: Reviews are returned in descending order by their helpfulness score.
        - name: limit
          in: query
          schema:
            type: integer
            default: 10
            minimum: 1
            maximum: 100
          description: A limit on the number of Reviews to be returned. 
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  object:
                    type: string
                    const: 'list'
                    description: Constant string `list`, representing the object's type. Objects of the same type share the same value.
                  data:
                    type: array
                    items:
                      allOf:
                        - $ref: '#/components/schemas/Review'
                        - type: object
                          properties:
                            user:
                              $ref: '#/components/schemas/User'
                  next_page_url:
                    oneOf:
                      - type: string
                        format: url
                      - type: 'null'
                  prev_page_url:
                    oneOf:
                      - type: string
                        format: url
                      - type: 'null'
        '404':
          description: Not Found
    post:
      tags:
        - Reviews
      summary: Post a Review of a Place
      security:
        - oAuth2: []
      x-badges:
        - name: 'Authentication required'
          position: before
          color: '#FFB56A'
      parameters:
        - name: place_id
          in: path
          required: true
          schema:
            $ref: '#/components/schemas/Place/properties/id'
          example: plc_nReHKJVfxZbhxmvi36r4rQ
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                recommends:
                  description: Whether the user recommends this Place.
                  type: boolean
                comment:
                  description: "The user's comment about the Place, if any."
                  oneOf:
                    - type: string
                    - type: 'null'
      responses:
        '202':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Review'
        '404':
          description: Not Found
  /v1/reviews/{review_id}:
    get:
      tags:
        - Reviews
      summary: Retrieve a Review
      parameters:
        - name: review_id
          in: path
          required: true
          schema:
            $ref: '#/components/schemas/Review/properties/id'
          example: rvw_nReHKJVfxZbhxmvi36r4rQ
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/Review'
                  - type: object
                    properties:
                      user:
                        $ref: '#/components/schemas/User'
                  - type: object
                    properties:
                      place:
                        $ref: '#/components/schemas/Place'
        '404':
          description: Not Found
    put:
      tags:
        - Reviews
      summary: Update a Review
      security:
        - oAuth2: []
      x-badges:
        - name: 'Authentication required'
          position: before
          color: '#FFB56A'
      parameters:
        - name: review_id
          in: path
          required: true
          schema:
            $ref: '#/components/schemas/Review/properties/id'
          example: rvw_nReHKJVfxZbhxmvi36r4rQ
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                recommends:
                  description: Whether the user recommends this Place.
                  type: boolean
                comment:
                  description: "The user's comment about the Place, if any."
                  oneOf:
                    - type: string
                    - type: 'null'
              example:
                recommends: true
                comment: Great place! It has a really cute cafe as well and an observatory that you can visit during the week.
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Review'
        '404':
          description: Not Found
    delete:
      tags:
        - Reviews
      summary: Delete a Review
      security:
        - oAuth2: []
      x-badges:
        - name: 'Authentication required'
          position: before
          color: '#FFB56A'
      parameters:
        - name: review_id
          in: path
          required: true
          schema:
            $ref: '#/components/schemas/Review/properties/id'
          example: rvw_nReHKJVfxZbhxmvi36r4rQ
      responses:
        '204':
          description: Successful Response (No Content)
        '404':
          description: Not Found
  /v1/reviews/{review_id}/mark_helpful:
    put:
      tags:
        - Reviews
      summary: Mark a Review as helpful
      description: |
        Mark a Review as helpful, which is to indicate to other users that the
        commentary in this Review is useful and informative.

        We believe that user reviews are inherently subjective and we welcome
        them as such. However, we also acknowledge that some comments are more
        useful and informative than others. Therefore, we provide a way for
        users to mark helpful reviews as such to let helpful reviews reach a
        broader audience.
      security:
        - oAuth2: []
      x-badges:
        - name: 'Authentication required'
          position: before
          color: '#FFB56A'
      parameters:
        - name: review_id
          in: path
          required: true
          schema:
            $ref: '#/components/schemas/Review/properties/id'
          example: rvw_nReHKJVfxZbhxmvi36r4rQ
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Review'
        '404':
          description: Not Found
  /v1/reviews/{review_id}/unmark_helpful:
    put:
      tags:
        - Reviews
      summary: Remove helpful marking on a Review
      security:
        - oAuth2: []
      x-badges:
        - name: 'Authentication required'
          position: before
          color: '#FFB56A'
      parameters:
        - name: review_id
          in: path
          required: true
          schema:
            $ref: '#/components/schemas/Review/properties/id'
          example: rvw_nReHKJVfxZbhxmvi36r4rQ
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Review'
        '404':
          description: Not Found
  /v1/reviews/{review_id}/flag:
    put:
      tags:
        - Reviews
      summary: Flag a Review
      description: |
        Flag a Review for moderator consideration, to report a potential breach
        of rules.

        Because there isn't a way to undo, clients MUST ask the user for
        confirmation before flagging a Review.
      security:
        - oAuth2: []
      x-badges:
        - name: 'Authentication required'
          position: before
          color: '#FFB56A'
      parameters:
        - name: review_id
          in: path
          required: true
          schema:
            $ref: '#/components/schemas/Review/properties/id'
          example: rvw_nReHKJVfxZbhxmvi36r4rQ
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Review'
        '404':
          description: Not Found
  /v1/users/{user_id}:
    get:
      tags:
        - Users
      summary: Retrieve a User
      parameters:
        - name: user_id
          in: path
          required: true
          schema:
            $ref: "#/components/schemas/User/properties/id"
          example: usr_nReHKJVfxZbhxmvi36r4rQ
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
        '404':
          description: Not Found
components:
  schemas:
    Place:
      type: object
      properties:
        object:
          type: string
          const: 'place'
          description: Constant string `place`, representing the object's type. Objects of the same type share the same value.
        id:
          description: Unique ID of this Place.
          type: string
          pattern: '^plc_[a-zA-Z0-9]+$'
        name:
          description: Name of this Place.
          type: string
        location:
          description: |
            Geographic coordinates of this Place using the standard WGS84 projection.

            While storing and processing coordinates, do not use IEEE 32-bit floating point data type since it is limited to about 5 decimal places for the highest longitude whereas we use 7 decimal places.
          type: object
          properties:
            lat:
              description: Latitude coordinate in degrees (North of equator is positive).
              type: number
              format: double
              minimum: -90
              maximum: 90
            lon:
              description: Longitude coordinate in degrees (East of Greenwich is positive).
              type: number
              format: double
              minimum: -180
              maximum: 180
        review_stats:
          description: Statistics about the reviews users wrote about this Place.
          type: object
          properties:
            count:
              description: Number of reviews written.
              type: integer
              minimum: 0
            like_ratio:
              description: Ratio of reviews which liked this Place to all reviews.
              type: number
              minimum: 0
              maximum: 1
            rank:
              description: A measure of how much liked this Place is (higher is better), factoring in the recency of its reviews and the total number of reviews. We assume that reviews lose their relevance over time and more reviews give us greater confidence the likeability of a Place.
              type: number
              minimum: 0
              maximum: 1
      example:
        object: 'place'
        id: 'plc_nReHKJVfxZbhxmvi36r4rQ'
        name: 'Blackrock Castle'
        location:
          lat: 51.9001065
          lon: -8.4024855
          review_stats:
            count: 2317
            like_ratio: 0.9297861
            rank: 0.9176327
    Review:
      type: object
      properties:
        object:
          type: string
          const: 'review'
          description: Constant string `review`, representing the object's type. Objects of the same type share the same value.
        id:
          type: string
          description: Unique ID of this Review.
          pattern: '^rvw_[a-zA-Z0-9]+$'
        created:
          type: string
          description: Timestamp of when this Review was created.
          format: date-time
        place:
          description: The Place that the `user` is reviewing. Expandable.
          type: object
          properties:
            id:
              $ref: '#/components/schemas/Place/properties/id'
        user:
          type: object
          description: The User who authored this Review. Expandable.
          properties:
            id:
              $ref: '#/components/schemas/User/properties/id'
        recommends:
          type: boolean
          description: Whether author of this Review recommends this Place to others.
        comment:
          description: "The user's comments about the Place, if any."
          oneOf:
            - type: string
            - type: 'null'
        marked_helpful_at:
          description: Timestamp of when the user who is making the API call marked this Review as helpful, if ever.
          oneOf:
            - type: string
              format: date-time
            - type: 'null'
        helpful_stats:
          type: object
          description: Statistics about the helpfulness of this Review as indicated by other users.
          properties:
            count:
              type: integer
              description: Number of users who found this Review helpful.
              minimum: 0
            score:
              type: number
              description: A measure of how helpful this Review is, factoring in its recency (higher is better). We assume that Reviews lose their relevance over time and become less helpful.
              minimum: 0
      example:
        object: 'review'
        id: 'rvw_nReHKJVfxZbhxmvi36r4rQ'
        created: '2025-09-21T12:20:56.142Z'
        place:
          id: 'plc_nReHKJVfxZbhxmvi36r4rQ'
        user:
          $ref: '#/components/schemas/User/example'
        recommends: true
        comment: 'Great place! It has a really cute cafe as well and an observatory that you can visit anytime.'
        marked_helpful_at: null
        helpful_stats:
          count: 7
          score: 6.98832
    User:
      type: object
      properties:
        object:
          type: string
          const: 'user'
          description: Constant string `user`, representing the object's type. Objects of the same type share the same value.
        id:
          description: Unique ID of the User.
          type: string
          pattern: '^usr_[a-zA-Z0-9]+$'
        name:
          description: Name of the User, which can be their real name or nickname and does not have to be unique.
          type: string
      example:
        object: 'user'
        id: 'usr_nReHKJVfxZbhxmvi36r4rQ'
        name: 'bora'
    Error:
      type: object
      properties:
        message:
          description: A human-readable message in English providing more details about the error. You should not show these messages to your users.
          type: string
        code:
          description: For exceptions that are not programmer errors and that you can handle programmatically, an enum indicating what the issue is.
          oneOf:
            - type: string
            - type: 'null'

  securitySchemes:
    oAuth2:
      type: oauth2
      description: This API uses OAuth 2 with the implicit grant flow. [More info](https://api.example.com/docs/auth)
      flows:
        authorizationCode:
          x-usePkce: true
          authorizationUrl: https://api.example.com/oauth2/authorize
          scopes:
            write_reviews: Create, update, and delete your reviews on your behalf.
  responses:
    BadRequest:
      description: Bad Request. Typically due to malformed request syntax or invalid request body.
    
tags:
  - name: Places
    description: A **Place** is a Point of Interest (POI) in the world, such as a museum, a cafe, or a park.
  - name: Reviews
    description: A **Review** is a subjective assessment of a Place for the information of other users.
  - name: Users
    description: A **User** is a person who visits Places and reads & writes Reviews of them.
